spring.application.name=example
startValue = 1000
endValue = 2000
distanceStart = 0
distanceEnd = 10
url = jdbc:postgresql://192.168.0.108:5433/example_DB
login = admin
password = admin
pathToFileForRead = src/main/resources/file.txt
pathToFileForWrite = src/main/resources/entities.txt
management.endpoints.web.exposure.include = health,prometheus
management.metrics.export.prometheus.enabled = true
management.metrics.distribution.percentiles-histogram.[http.server.requests]=true
server.tomcat.mbeanregistry.enabled=true